const movies = [
    {
        "adult": false,
        "backdrop_path": "/xi1VSt3DtkevUmzCx2mNlCoDe74.jpg",
        "genre_ids": [
            35,
            14,
            27
        ],
        "id": 917496,
        "original_language": "en",
        "original_title": "Beetlejuice Beetlejuice",
        "overview": "After a family tragedy, three generations of the Deetz family return home to Winter River. Still haunted by Betelgeuse, Lydia's life is turned upside down when her teenage daughter, Astrid, accidentally opens the portal to the Afterlife.",
        "popularity": 3803.758,
        "poster_path": "/kKgQzkUCnQmeTPkyIwHly2t6ZFI.jpg",
        "release_date": "2024-09-04",
        "title": "Beetlejuice Beetlejuice",
        "video": false,
        "vote_average": 7.19,
        "vote_count": 1236,
        "border_color": "#2a3c65",
        "text_color": "#cd6f81",
    },
    {
        "adult": false,
        "backdrop_path": "/3m0j3hCS8kMAaP9El6Vy5Lqnyft.jpg",
        "genre_ids": [
            878,
            53,
            18,
            27
        ],
        "id": 1125510,
        "original_language": "es",
        "original_title": "El hoyo 2",
        "overview": "After a mysterious leader imposes his law in a brutal system of vertical cells, a new arrival battles against a dubious food distribution method.",
        "popularity": 3286.65,
        "poster_path": "/izuzUb0sDokqp9o8utVfsrSJuy5.jpg",
        "release_date": "2024-09-27",
        "title": "The Platform 2",
        "video": false,
        "vote_average": 5.702,
        "vote_count": 514,
        "border_color": "#2f6374",
        "text_color": "#cdd8da",
    },
    {
        "adult": false,
        "backdrop_path": "/7h6TqPB3ESmjuVbxCxAeB1c9OB1.jpg",
        "genre_ids": [
            27,
            18,
            878
        ],
        "id": 933260,
        "original_language": "en",
        "original_title": "The Substance",
        "overview": "A fading celebrity decides to use a black market drug, a cell-replicating substance that temporarily creates a younger, better version of herself.",
        "popularity": 2987.089,
        "poster_path": "/lqoMzCcZYEFK729d6qzt349fB4o.jpg",
        "release_date": "2024-09-07",
        "title": "The Substance",
        "video": false,
        "vote_average": 7.4,
        "vote_count": 412,
        "border_color": "#c08886",
        "text_color": "#cdd8da",
    },
    {
        "adult": false,
        "backdrop_path": "/xlkclSE4aq7r3JsFIJRgs21zUew.jpg",
        "genre_ids": [
            27,
            53
        ],
        "id": 1034541,
        "original_language": "en",
        "original_title": "Terrifier 3",
        "overview": "Five years after surviving Art the Clown's Halloween massacre, Sienna and Jonathan are still struggling to rebuild their shattered lives.",
        "popularity": 2157.641,
        "poster_path": "/7NDHoebflLwL1CcgLJ9wZbbDrmV.jpg",
        "release_date": "2024-10-09",
        "title": "Terrifier 3",
        "video": false,
        "vote_average": 7.24,
        "vote_count": 48,
        "border_color": "#05060e",
        "text_color": "#c4cdd9",
    },
    {
        "adult": false,
        "backdrop_path": "/hPIWQT70wQK6akqfLXByEvr62u0.jpg",
        "genre_ids": [
            28,
            53,
            27,
            878
        ],
        "id": 726139,
        "original_language": "ko",
        "original_title": "탈출: 프로젝트 사일런스",
        "overview": "Due to sudden deteriorating weather conditions, visibility on the Airport Bridge is severely impaired, leaving people stranded and at risk of the bridge collapsing due to a series of chain collisions and explosions.",
        "popularity": 1731.257,
        "poster_path": "/fttoFfKikQMwIoV3UVvlCvBhbUw.jpg",
        "release_date": "2024-07-11",
        "title": "Project Silence",
        "video": false,
        "vote_average": 7.1,
        "vote_count": 162,
        "border_color": "#7ca4b4",
        "text_color": "#c4cdd9",
    },
];

export default movies;